### ISSUE TITLE
模块设置替换失败

### ISSUE THREAD

**Issue by tehcneko** [SakuraKoi/DgLabUnlocker#14]
```
----part 3 start----
[ 2022-05-17T21:02:33.441    10264: 27190: 27190 I/LSPosed-Bridge  ] Loading module sakura.kooi.dglabunlocker from /data/app/~~NXu5diOZ8Mwa5oRukWwDCg==/sakura.kooi.dglabunlocker-ZTL1k6_2f8085EeGGs__eQ==/base.apk
[ 2022-05-17T21:02:33.463    10264: 27190: 27190 I/LSPosed-Bridge  ]   Loading class sakura.kooi.dglabunlocker.XposedModuleInit
[ 2022-05-17T21:02:33.725    10264: 27190: 27190 E/LSPosed-Bridge  ] java.lang.VerifyError: Verifier rejected class sakura.kooi.dglabunlocker.variables.ModuleSettings: void sakura.kooi.dglabunlocker.variables.ModuleSettings.showSettingsDialog(android.content.Context) failed to verify: void sakura.kooi.dglabunlocker.variables.ModuleSettings.showSettingsDialog(android.content.Context): [0x2] void sakura.kooi.dglabunlocker.variables.ModuleSettings.showSettingsDialog(android.content.Context): [0x2] 'this' argument 'Reference: java.lang.invoke.MethodHandle' not instance of 'Precise Reference: java.lang.invoke.MethodHandles$Lookup' (declaration of 'sakura.kooi.dglabunlocker.variables.ModuleSettings' appears in Anonymous-DexFile@1437296361)
	at sakura.kooi.dglabunlocker.variables.ModuleSettings.loadConfiguration(Unknown Source:0)
	at sakura.kooi.dglabunlocker.XposedModuleInit.onAppLoaded(XposedModuleInit.java:109)
	at sakura.kooi.dglabunlocker.XposedModuleInit.access$000(XposedModuleInit.java:37)
	at sakura.kooi.dglabunlocker.XposedModuleInit$1.afterHookedMethod(XposedModuleInit.java:87)
	at KC.Aa.LLWKGBiWaQht.nrd.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:338)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
应用为 1.2.6，模块为 v6-fix

**Comment by tehcneko** [comment]
应该是 LSPosed 的 dex obfuscation 的问题，已经反馈给他们了（
