### ISSUE TITLE
导入波形crash

### ISSUE THREAD

**Issue by SakuraKoi** [SakuraKoi/DgLabUnlocker#38]
```
01-27 17:01:27.475 25012 25012 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.bjsm.dungeonlab.bean.BaseDataBean.getRate()' on a null object reference
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.bjsm.dungeonlab.ui.fragment.PlayFragment3.m(PlayFragment3.java:1373)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.bjsm.dungeonlab.ui.fragment.PlayFragment3.f(PlayFragment3.java:442)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.bjsm.dungeonlab.base.BaseFragment.e(BaseFragment.java:169)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.bjsm.dungeonlab.ui.fragment.PlayFragment3_.a(PlayFragment3_.java:624)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at org.a.a.b.c.a(OnViewChangedNotifier.java:41)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.bjsm.dungeonlab.ui.fragment.PlayFragment3_.onViewCreated(PlayFragment3_.java:164)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.bjsm.dungeonlab.base.BaseActivity.onStart(BaseActivity.java:310)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8315)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-27 17:01:27.475 25012 25012 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
按完导入直接崩溃 v1.3.2

**Comment by SakuraKoi** [comment]
NPE位置
```
switch ((this.f2881aH == 1 ? Constants.f771ai : Constants.f772aj).getRate()) {
```
考虑event导致的值改变
```
EventBus.m65a().m47d(new EventBusMsg(1)); -> PlayFragment3
```

TODO: 尝试一下导入波形前拦截Eventbus投递消息

**Comment by SakuraKoi** [comment]
放弃当前版本支持, 准备上手beta
